copyright: 2021 - 2023 GL513
site_name: GL513 Github Pages
site_url: https://GL513.github.io/
site_description: GL513 Github Pages
repo_url: https://github.com/GL513/GL513.github.io
repo_name: GL513 Github Pages
nav:
    - Home: index.md
    - Blog: blog/index.md
    - Feed: feed/index.md
    - Music: music/index.md
    - Archives: archives/index.md
    - Projects:
        - 0jEdge: projects/0jEdge/0jEdge.md
        - Key Mapper: projects/keymapper/keymapper.md
        - ChatKC: projects/chatKC/chatKC.md
    - Pages: pages/index.md
    - About:
        - About GL: about/gl.md
        - Contributing: about/contributing.md
        - Rundown: about/rundown.md
        - Tabs:
            - Projects: about/projects.md
            - Archives: about/archives.md
theme:
  logo: img/glLogo.png
  favicon: img/glLogolowres.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.expand
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.indexes

  font:
    text: Inconsolata
  name: material
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - tags:
      tags_file: tags.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - def_list
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: 🔗
extra:

# consent:
#    actions:
#      - accept
#      - manage
#      - reject
#     cookies:
#      analytics: Google Analytics
#      custom: Widgetbot
#     title: Cookie consent
#     description: >-
#      Hello, it's me, Gavin. This message is here specifically for the European Union's [ePrivacy Directive](https://gdpr.eu/cookies/).
 generator: false
 analytics:
    provider: google
    property: G-PZXKZNXKYR
 social:
  - icon: fontawesome/brands/github
    link: https://github.com/gl513
    name: GL513 Github

  - icon: simple/mastodon
    link: https://mastodon.world/@GL513
    name: GL513 Mastodon

  - icon: simple/discord
    link: /out/discord
    name: GL513 Discord

  - icon: fontawesome/brands/reddit-alien
    link: https://reddit.com/u/GL513
    name: GL513 Reddit

  - icon: simple/internetarchive
    link: https://archive.org/details/@gl513
    name: GL513 Archive.org

  - icon: fontawesome/brands/soundcloud
    link: https://soundcloud.com/GL513
    name: GL513 SoundCloud

  - icon: simple/bandcamp
    link: https://GL513.bandcamp.com/
    name: GL513 Bandcamp

  - icon: simple/gmail
    link: mailto:developer.gl513@gmail.com
    name: GL513 Email
